kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.7
  commands:
  - pip install -r dev-requirements.txt
  - git clone --depth=1 https://github.com/pyca/pyopenssl
  - cd pyopenssl
  - git rev-parse HEAD
  - pip install -e ".[test]"
  - pytest tests
