kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.8
  commands:
  - export TOXENV="py38"
  - export DOCKER="pyca/cryptography-runner-bullseye"
  - ./.travis/install.sh
  - ./.travis/run.sh
