---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: python:3.8
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
  commands:
    - export CRYPTOGRAPHY_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$CRYPTOGARPHY_ROOT/.travis"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - sed -i '$ichown -R conda:conda "$CRYPTOGRAPHY_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $CRYPTOGRAPHY_ROOT/.travis/install.sh
    - /opt/docker/bin/entrypoint $CRYPTOGRAPHY_ROOT/.travis/run.sh
    - /opt/docker/bin/entrypoint $CRYPTOGRAPHY_ROOT/.travis/upload_coverage.sh
    - /opt/docker/bin/
    - echo "Done building"
