kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python:3.8
  commands:
  - export DOWNSTREAM="0"
  - export OPENSSL="1.1.0l"
  - ./.travis/install.sh
  - ./.travis/run.sh
