---
kind: pipeline
name: linux_aarch64_

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: python:3.8
  environment:
    CONFIG: linux_aarch64_
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
  commands:
    - apt-get install -y ruby
    - ./.travis/install.sh
    - ./.travis/run.sh
    - ./.travis/upload_coverage.sh
    - echo "Done building"
