kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
- name: test
  image: python
  commands:
  - export DOWNSTREAM=twisted OPENSSL=1.1.1g
  - ./.travis/install.sh
  - ./.travis/run.sh
